### PR TITLE
Fix '*' with private repo

### PR DESCRIPTION
**Pull request by simahawk**
When you use '*' to catch all repos
and you have a private repo right after
the private repo-specific setting
is not taken into account
hence the checkout will fail
and you'll be asked to login via https.

Also, seems useless to compute repo data
if we have a specific one declared.

Example:
```
github.com:
  "*":
    orgs:
      - OCA
      - camptocamp

  enterprise:
     orgs:
       - odoo
       - camptocamp
     private: True

  private-specific:
     orgs:
       - camptocamp
     private: True
```

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul ping :)

**Comment by sbidoul** [comment]
Out of curiosity, what's is not working with a config like this ? Everything goes via ssh, but is that an issue in practice ?

```
github.com:
  "*":
    orgs:
      - acsone
      - OCA
      - odoo
    private: True
```

**Comment by simahawk** [comment]
@sbidoul wait... I didn't know I could set the `private` flag in the same section. I thought it was meant to indicate specific private repos only. 

Ok, cool, this eliminates the https problem in general. Still, the issue of a possible repo-specific override remains.

**Comment by sbidoul** [comment]
> Still, the issue of a possible repo-specific override remains.

Sure. But is there a real use case remaining for these overrides ? (just trying to avoid work here :)

**Comment by simahawk** [comment]
@sbidoul in fact, is working now. I'll propose a change for the readme to clarify such use cases maybe.

**Pull request closed without merging**
